apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      replicated: db
  template:
    metadata:
      name: postgres-pod
      labels:
        replicated: db
        service: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres
        ports:
        - containerPort: 5439
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
