apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      replicated: res
  template:
    metadata:
      name: result-app-pod
      labels:
        replicated: res
        service: result
    spec:
      containers:
      - name: result-app-container
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
