apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      replicated: work
  template:
    metadata:
      name: worker-pod
      labels:
        replicated: work
    spec:
      containers:
      - name: worker-container
        image: dockersamples/examplevotingapp_worker
