apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      replicated: vote
  template:
    metadata:
      name: voting-app-pod
      labels:
        replicated: vote
        service: voting
    spec:
      containers:
      - name: voting-app-container
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
